// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1BNcnSdFbwqj5kEN3KI0Pf1m1IYXIBQo',
    appId: '1:372683523114:android:d29cea64f2b325b8c2ef53',
    messagingSenderId: '372683523114',
    projectId: 'roti-nyaman',
    storageBucket: 'roti-nyaman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClNn1vomOypGe1NrKK1e7p4iEuvSM4xA8',
    appId: '1:372683523114:ios:b1fd081642ddd2fdc2ef53',
    messagingSenderId: '372683523114',
    projectId: 'roti-nyaman',
    storageBucket: 'roti-nyaman.firebasestorage.app',
    androidClientId:
        '372683523114-2rq46r1q7ihehc3vcs769eo2sr8gq0ol.apps.googleusercontent.com',
    iosClientId:
        '372683523114-vkdk14v3sauf8q8ek431a84e3224v6qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rotiNyaman',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD2yRH0krubN1GimRgrV9fFVe210-iApzY",
    authDomain: "roti-nyaman.firebaseapp.com",
    projectId: "roti-nyaman",
    storageBucket: "roti-nyaman.firebasestorage.app",
    messagingSenderId: "372683523114",
    appId: "1:372683523114:web:690f9bd5f57ca999c2ef53",
    measurementId: "G-H22EZ0N6LF",
  );
}
