// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdK62JzK0G07y4KLraACGlHetMTVHEUb8',
    appId: '1:2427366198:web:e7964f6d0ba7767ba7a197',
    messagingSenderId: '2427366198',
    projectId: 'app-with-firebase-da00e',
    authDomain: 'app-with-firebase-da00e.firebaseapp.com',
    storageBucket: 'app-with-firebase-da00e.firebasestorage.app',
    measurementId: 'G-H5M7HXLDRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4a53_HUhvAhXg9t8wb4ooj-Bj_C6u09Q',
    appId: '1:2427366198:android:1ef9bb08f9834ff0a7a197',
    messagingSenderId: '2427366198',
    projectId: 'app-with-firebase-da00e',
    storageBucket: 'app-with-firebase-da00e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXOIMo3s1n8uOMB4mtkMt8iLKipkSVAY',
    appId: '1:2427366198:ios:c1e0933dd24408a7a7a197',
    messagingSenderId: '2427366198',
    projectId: 'app-with-firebase-da00e',
    storageBucket: 'app-with-firebase-da00e.firebasestorage.app',
    iosBundleId: 'com.example.uasWithFirbase',
  );
}
